services:
    # Development service
    leb-website-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: leb-website-dev
        ports:
            - '9000:9000'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - HOST=0.0.0.0
            - PORT=9000
            - GRAPHQL_URL=${GRAPHQL_URL:-https://graphql.db-bocom.at/}
            - VITE_GRAPHQL_URL=${GRAPHQL_URL:-https://graphql.db-bocom.at/}
        networks:
            - leb-network

networks:
    leb-network:
        driver: bridge

volumes:
    node_modules:
