services:
    # Production service
    leb-website-prod:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        container_name: leb-website-prod
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - VITE_GRAPHQL_URL=${GRAPHQL_URL:-https://graphql.db-bocom.at/}
            - VITE_IMAGE_URL=${VITE_IMAGE_URL:-https://fier.levelling.app/images/}
        networks:
            - leb-network

networks:
    leb-network:
        driver: bridge
