services:
    # Production service
    leb-website-prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: leb-website-prod
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - VITE_GRAPHQL_URL=${VITE_GRAPHQL_URL}
            - VITE_IMAGE_URL=${VITE_IMAGE_URL}
        networks:
            - leb-network

networks:
    leb-network:
        driver: bridge
